Major update 4.x.x
SiruBOT/SiruBOT pull request #99
Opened 2021-10-28 00:19 UTC by Sannoob3144

### Internal
- [x] Config update (js -> yaml)
- [x] Typescript rewrite (in progress!)
- [x] slash Command (message intent)
- [x] Discord.JS v13 migration (12.5 -> 13.5)
- [x] shoukaku migration (v1.0 -> 2.x)
- [x] Use discord-hybrid-sharding (reduce resource for sharding)
- [x] Update CI
- [x] SLyrics Rewrite (https://github.com/SiruBOT/slyrics/tree/1.0)
- [ ] ~~Auto reconnect (db, lavalink)~~
### Features
- [ ] Lavalink filters
- [ ] Custom playlist
- [x] Message components
### Planned
- [ ] Youtube OAuth2 playlist import, export

2021-12-07 11:20 UTC, sannoob commented
@all-contributors bot

2021-12-07 11:21 UTC, sannoob commented
@all-contributors please add @sannoob for Code

2021-12-09 13:29 UTC, zero734kr requested changes

2021-12-09 13:29 UTC, zero734kr commented on .github/workflows/node.js.yml
> +      run: yarn run build # Typescript 프로젝트를 빌드합니다
How about adding the "--noEmit" option since this build is not being used after it was created?

2021-12-09 13:29 UTC, zero734kr commented on package.json
> +    "@types/yaml": "^1.9.7",
Move typing deps to devDependencies

2021-12-09 13:29 UTC, zero734kr commented on src/index.ts
> +import { existsSync, readFileSync } from "fs";
Don't use synchronous methods, use fs/promises instead.


```suggestion
import { exists, readFile } from "fs/promises";
```

2021-12-09 13:29 UTC, zero734kr commented on src/index.ts
> +}
```suggestion
async function readFile(path: string): Promise<string> {
  const fileExists = await exists(path);
  if (!fileExists) throw new Error(`File ${path} does not exist`);
  if (typeof path == "string" && !path.endsWith(".yaml"))
    throw new Error(`File ${path} is not a YAML file`);
  return readFile(path, "utf-8");
}
```

2021-12-09 13:29 UTC, zero734kr commented on src/index.ts
> +console.log(parsedConfig);
```suggestion
async function printConfig() {
  const fileContent = await readFile(args.config);
  const parsedConfig: ISettings = parse(fileContent);
  console.log(parsedConfig);
}

printConfig()
```

2021-12-09 13:35 UTC, sannoob commented on package.json
> +    "@types/yaml": "^1.9.7",
Okay, I will add it

2021-12-09 14:04 UTC, sannoob commented on package.json
> +    "@types/yaml": "^1.9.7",
Resolved in https://github.com/SiruBOT/SiruBOT/pull/99/commits/9f6ebd897086b7260cb68317438a26bf8f66f710

2021-12-09 14:08 UTC, sannoob commented on .github/workflows/node.js.yml
> +      run: yarn run build # Typescript 프로젝트를 빌드합니다
Resolved in https://github.com/SiruBOT/SiruBOT/pull/99/commits/cbea94c12c15e02d32cf72a0f1e91073edecd906

2022-04-25 04:52 UTC, sannoob commented on src/bot.ts
> +  throw "Failed to parse process.argv[2] and process.argv[3] (Bot config and Bootstrapper args)";
String 을 throw 하는 대신 new Error 사용하기

2022-04-25 04:52 UTC, sannoob commented on src/commands/audio/NowplayingCommand.ts
> +    await interaction.reply({ content: "이이이잉 앗살라말라이쿰" });
WIP

2022-07-17 23:51 UTC, merged